server:
  port: 8088
spring:
  encrypt:
    key: ABCDEF9876543210
    debug: false
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 10MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.kcs.note.entity