server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://mysql.localdomain:3306/myproject?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;autoReconnect=true&amp;useSSL=false
    username: kcs
    password: 20142346
    driver-class-name: com.mysql.jdbc.Driver
  encrypt:
    key: ABCDEF9876543210
    debug: false
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 10MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.kcs.*.entity
#upload_folder_path
upload_folder_path: /Users/kcs/WebstormProjects/demo/static/